import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Github, ExternalLink, Code2, X, Sparkles, Layers, Cpu, Globe } from 'lucide-react';

const projects = [
  {
    id: "devos",
    title: "DevOS",
    subtitle: "Developer Continuity Engine",
    description: "Solving context-switching overhead by persisting absolute project state, tasks, and Git history across OS sessions.",
    longDescription: "DevOS is a context-aware execution environment that eliminates the 'cold start' problem for developers. It tracks terminal history, open files, and git state, allowing you to resume exactly where you left off. Integrated with Groq LLaMA-3.3-70b for intelligent context retrieval.",
    arch: "Agentic AI with function-calling — LLaMA-3.3-70b as the core decision engine.",
    stack: ["React", "TypeScript", "Node.js", "MongoDB", "Groq"],
    accent: "#00FF87",
    link: "#",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "khudkojano",
    title: "KhudKoJano",
    subtitle: "AI Astrology Platform",
    description: "Client project featuring AI-powered personalized astrology reports with integrated payment flows and automated PDF generation.",
    longDescription: "A comprehensive SaaS platform where users receive deep astrological insights generated by LLMs. Features include secure payment integration, automated high-fidelity PDF generation, and a subscription-based model. Built for high conversion and seamless user onboarding.",
    arch: "LLM-orchestrated content generation with secure webhook-verified payment processing and headless Chrome PDF rendering.",
    stack: ["React", "Node.js", "MongoDB", "Razorpay", "LLM", "Puppeteer"],
    accent: "#FFBD2E",
    link: "https://khudkojano.onrender.com/",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "ecoex",
    title: "EcoEx",
    subtitle: "Carbon Footprint Predictor",
    description: "Hackathon-winning ML project that predicts carbon footprints and power consumption for industrial entities.",
    longDescription: "EcoEx uses a custom-trained ML model to analyze industrial data and predict environmental impact. It provides actionable future insights and power consumption forecasts, allowing industries to optimize their sustainability goals.",
    arch: "FastAPI inference microservice decoupled from the main React/Node stack for independent scaling and high-performance predictions.",
    stack: ["React", "FastAPI", "Python", "Scikit-Learn", "Node.js"],
    accent: "#3BFCFF",
    link: "https://ecoex.onrender.com/",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "climx",
    title: "ClimX",
    subtitle: "Construction Risk AI",
    description: "Weather-aware disaster risk assessment tool for construction projects. Predictive safety auditing.",
    longDescription: "ClimX analyzes historical and real-time weather data to evaluate the safety of construction sites. It suggests architectural and logistical changes to mitigate risks from natural disasters in specific geographic areas.",
    arch: "Geospatial data indexing combined with real-time weather API integration and predictive risk scoring algorithms.",
    stack: ["React", "Weather API", "Node.js", "Geospatial Indexing"],
    accent: "#FF5F57",
    link: "https://climx.onrender.com/",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "anay",
    title: "Anay",
    subtitle: "Conversational AI Assistant",
    description: "A Jarvis-style companion that interacts naturally and performs tasks through voice and chat.",
    longDescription: "Anay is designed to feel like a friend rather than a tool. It features ultra-low latency voice interaction, personality-driven responses, and the ability to execute system commands and manage tasks via agentic workflows.",
    arch: "Stream-based audio processing with LLM function-calling for real-time task execution and companion-like personality tuning.",
    stack: ["React", "OpenAI / Groq", "Node.js", "WebSockets", "Web Speech API"],
    accent: "#8A2BE2",
    link: "https://anay-6p54.onrender.com/",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "krheat",
    title: "KR Heat Treatment",
    subtitle: "Industrial Business Portal",
    description: "Production-grade business website for a leading industrial heat treatment firm.",
    longDescription: "A high-performance, SEO-optimized business platform that showcases industrial processes and services. Built with a focus on professional aesthetics and lightning-fast load times for mobile and desktop users.",
    arch: "Static Site Generation (SSG) for maximum performance and SEO visibility, with serverless contact handling.",
    stack: ["React", "Tailwind CSS", "Framer Motion", "SEO Best Practices"],
    accent: "#CDD9E5",
    link: "https://kr-heat-treatment.vercel.app/",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "edugenius",
    title: "EduGenius",
    subtitle: "Google Hackathon Entry",
    description: "AI-powered learning platform bridging the gap between teachers and students through automated systems.",
    longDescription: "EduGenius scales the educational experience by automating routine tasks for teachers and providing personalized learning paths for students. My first full-stack project, built for a prestigious Google Hackathon.",
    arch: "Full-stack MERN architecture with AI-driven content tagging and student-teacher communication conduits.",
    stack: ["MongoDB", "Express", "React", "Node.js", "AI Integration"],
    accent: "#4285F4",
    link: "https://sahilkhurana01.github.io/EduGenius-AI-Powered-Learning-Platfrom/",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "disaster",
    title: "Response HQ",
    subtitle: "Emergency Portal",
    description: "High-concurrency disaster management system with real-time alert broadcasting.",
    longDescription: "Response HQ is a mission-critical platform for emergency services. It uses WebSockets to maintain a live connection between dispatchers and field agents, ensuring sub-second response times during crises.",
    arch: "Dual-portal RBAC system with WebSocket-driven live updates and high-concurrency event handling.",
    stack: ["React", "Socket.io", "Node.js", "Express", "MongoDB"],
    accent: "#00FF87",
    link: "#",
    github: "https://github.com/VanshArora01"
  },
  {
    id: "ranglapunjab",
    title: "Rangla Punjab",
    subtitle: "NGO Service Portal",
    description: "Production-grade platform for a non-profit society, designed to showcase local societal contributions and humanitarian work.",
    longDescription: "A dedicated platform built for the Rangla Punjab Society to bridge the gap between their humanitarian initiatives and the digital audience. Features high-performance image galleries, contribution tracking, and a smooth, cinematic browsing experience for donors and volunteers.",
    arch: "Serverless architecture for mission-critical reliability and zero-cost scaling, with optimized asset delivery for humanitarian storytelling.",
    stack: ["React", "Tailwind CSS", "Framer Motion", "Vite"],
    accent: "#FF8C00",
    link: "http://rangla-punjab-society-front.onrender.com/",
    github: "https://github.com/VanshArora01"
  }
];

const ProjectCard = ({ project, onClick }) => {
  return (
    <motion.div
      layoutId={`card-${project.id}`}
      onClick={() => onClick(project)}
      whileHover={{ y: -10, scale: 1.02 }}
      className="glass work-card"
      style={{
        borderRadius: '32px',
        padding: '2rem',
        cursor: 'pointer',
        height: '350px',
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'space-between',
        position: 'relative',
        overflow: 'hidden',
        border: '1px solid rgba(255, 255, 255, 0.03)'
      }}
    >
      <div style={{ position: 'absolute', top: 0, right: 0, padding: '1.5rem', opacity: 0.1 }}>
        <Sparkles size={100} color={project.accent} />
      </div>

      <div>
        <div style={{ color: project.accent, fontSize: '0.8rem', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.2em', marginBottom: '1rem' }}>
          {project.subtitle}
        </div>
        <h3 style={{ fontSize: '2rem', fontWeight: 800, color: '#F0F6FC' }}>
          {project.title}
        </h3>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap', alignItems: 'center' }}>
          {project.stack.slice(0, 3).map((tech) => (
            <span key={tech} style={{ 
              fontSize: '0.65rem', color: '#8B949E', background: 'rgba(255,255,255,0.04)', 
              padding: '4px 12px', borderRadius: '100px', whiteSpace: 'nowrap',
              border: '1px solid rgba(255,255,255,0.03)'
            }}>{tech}</span>
          ))}
          {project.stack.length > 3 && <span style={{ fontSize: '0.65rem', color: project.accent, fontWeight: 700, marginLeft: '2px' }}>+{project.stack.length - 3}</span>}
        </div>
        <motion.div 
          style={{ width: '40px', height: '40px', borderRadius: '12px', background: `${project.accent}15`, display: 'flex', alignItems: 'center', justifyContent: 'center', color: project.accent }}
        >
          <ExternalLink size={18} />
        </motion.div>
      </div>
    </motion.div>
  );
};

const Modal = ({ project, onClose }) => {
  if (!project) return null;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      style={{
        position: 'fixed', inset: 0, zIndex: 10000,
        background: 'rgba(3, 7, 8, 0.9)',
        backdropFilter: 'blur(20px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: '2rem'
      }}
      onClick={onClose}
    >
      <motion.div
        layoutId={`card-${project.id}`}
        onClick={(e) => e.stopPropagation()}
        className="glass"
        style={{
          width: '100%', maxWidth: '900px', borderRadius: '32px',
          padding: '2.5rem', position: 'relative',
          maxHeight: 'fit-content', overflow: 'hidden'
        }}
      >
        <button 
          onClick={onClose}
          style={{ position: 'absolute', top: '1.5rem', right: '1.5rem', background: 'none', border: 'none', color: '#6E7681', cursor: 'pointer', zIndex: 10 }}
        >
          <X size={24} />
        </button>

        <div className="modal-header-container" style={{ marginBottom: '1.5rem', paddingRight: '2rem' }}>
          <span style={{ color: project.accent, fontSize: '0.8rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.25em' }}>
            {project.subtitle}
          </span>
          <h2 style={{ fontSize: '2.5rem', fontWeight: 800, color: '#F0F6FC', marginTop: '0.25rem' }}>
            {project.title}
          </h2>
        </div>        <div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1.8fr) 1fr', gap: '2rem' }} className="modal-content">
          <div>
            <h4 style={{ color: '#F0F6FC', marginBottom: '0.5rem', fontSize: '1rem' }}>Experience Brief</h4>
            <p style={{ color: '#8B949E', lineHeight: 1.6, fontSize: '0.92rem', marginBottom: '1.5rem' }}>
              {project.longDescription}
            </p>

            <div className="modal-extra-info">
              <h4 style={{ color: '#F0F6FC', marginBottom: '0.5rem', fontSize: '1rem' }}>System Architecture</h4>
              <div className="glass" style={{ padding: '1.25rem', borderRadius: '16px', borderLeft: `4px solid ${project.accent}` }}>
                <p style={{ color: '#CDD9E5', fontSize: '0.88rem', lineHeight: 1.5 }}>{project.arch}</p>
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            <div>
              <h4 style={{ color: '#8B949E', marginBottom: '0.75rem', fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Technology Stack</h4>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                {project.stack.map(tech => (
                  <span key={tech} className="glass" style={{ padding: '4px 12px', borderRadius: '100px', fontSize: '0.7rem', color: '#F0F6FC' }}>{tech}</span>
                ))}
              </div>
            </div>

            <div style={{ marginTop: 'auto', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <motion.a 
                whileHover={{ scale: 1.02, y: -2 }}
                href={project.link} target="_blank" rel="noreferrer"
                style={{ 
                  background: project.accent, color: '#030708', padding: '0.8rem', 
                  borderRadius: '12px', textDecoration: 'none', fontWeight: 800,
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px',
                  fontSize: '0.9rem', boxShadow: `0 10px 20px -5px ${project.accent}33`
                }}
              >
                Launch App <ExternalLink size={16} />
              </motion.a>
              <motion.a 
                whileHover={{ scale: 1.02, y: -2 }}
                href={project.github} target="_blank" rel="noreferrer"
                style={{ 
                  background: 'rgba(255,255,255,0.05)', color: '#F0F6FC', padding: '0.8rem', 
                  borderRadius: '12px', textDecoration: 'none', fontWeight: 800,
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px',
                  fontSize: '0.9rem', border: '1px solid rgba(255,255,255,0.05)'
                }}
              >
                Source Code <Github size={16} />
              </motion.a>
            </div>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
};

const Work = () => {
  const [selectedProject, setSelectedProject] = useState(null);

  return (
    <div className="mesh-bg pb-dock" style={{ minHeight: '100vh', padding: '6rem 0 4rem' }}>
      <div style={{ maxWidth: '1300px', margin: '0 auto', padding: '0 2.5rem' }}>
        
        {/* Cinematic Heading */}
        <div style={{ textAlign: 'center', marginBottom: '6rem' }}>
          <motion.p 
            initial={{ opacity: 0, y: 10 }}
            whileInView={{ opacity: 1, y: 0 }}
            style={{ color: '#00FF87', fontSize: '0.9rem', fontWeight: 600, letterSpacing: '0.3em', textTransform: 'uppercase', marginBottom: '1rem' }}
          >
            Digital Showroom
          </motion.p>
          <motion.h1 
            className="text-glow"
            style={{ fontSize: 'clamp(2rem, 6vw, 3.8rem)', fontWeight: 800, color: '#F0F6FC' }}
          >
            Production <span style={{ color: '#00FF87' }}>Matrix.</span>
          </motion.h1>
          <motion.p style={{ color: '#6E7681', fontSize: '1rem', marginTop: '1.2rem', maxWidth: '650px', margin: '1.2rem auto 0' }}>
            A comprehensive grid of agentic systems, production client builds, and experimental architectures.
          </motion.p>
        </div>

        {/* Project Grid */}
        <div className="work-grid" style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(auto-fit, minmax(350px, 1fr))', 
          gap: '2rem' 
        }}>
          {projects.map((project) => (
            <ProjectCard key={project.id} project={project} onClick={setSelectedProject} />
          ))}
        </div>

        {/* Modal Overlay */}
        <AnimatePresence>
          {selectedProject && (
            <Modal project={selectedProject} onClose={() => setSelectedProject(null)} />
          )}
        </AnimatePresence>

      </div>

      <style>{`
        @media (max-width: 768px) {
          .modal-content { grid-template-columns: 1fr !important; gap: 2rem !important; }
          .modal-extra-info { display: none; }
          .modal-header-container { padding-right: 3.5rem !important; }
          .modal-header-container h2 { font-size: 1.8rem !important; }
        }
        @media (max-width: 640px) {
          .work-grid {
            grid-template-columns: 1fr !important;
            gap: 1rem !important;
          }
          .work-card {
            height: auto !important;
            min-height: 220px !important;
            padding: 1.25rem !important;
            border-radius: 20px !important;
          }
          .work-card h3 {
            font-size: 1.5rem !important;
          }
          .work-card > div:first-child {
            padding: 1rem !important;
          }
        }
      `}</style>
    </div>
  );
};

export default Work;